### ISSUE TITLE
About Results

### ISSUE THREAD

**Issue by kurvt** [manumathewthomas/CS523Project3#3]
![image](https://user-images.githubusercontent.com/18389361/35615489-3cf05d96-06ad-11e8-832b-d533e257ac13.png)
I pressed the Denoise button, but it seemed to add noise.

**Comment by manumathewthomas** [comment]
Did you train the network or used the CKPT file provided? I think our CKPT file is corrupted for some reason. I can upload the latest version when I get time but I would suggest you to train the n/w from scratch.

**Comment by kurvt** [comment]
Traceback (most recent call last):
  File "C:/ImageDenoisingGAN-master/train.py", line 91, in <module>
    train()
  File "C:/ImageDenoisingGAN-master/train.py", line 23, in train
    Dg = discriminator(Gz, reuse=True)
  File "C:\ImageDenoisingGAN-master\model.py", line 32, in discriminator
    conv1, conv1_weights = conv_layer(input, 4, 3, 48, 2, "d_conv1", reuse=reuse)
  File "C:\ImageDenoisingGAN-master\conv_helper.py", line 10, in conv_layer
    output = slim.batch_norm(output)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 528, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\layers\base.py", line 320, in apply
    return self.__call__(inputs, **kwargs)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\layers\base.py", line 286, in __call__
    self.build(input_shapes[0])
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\layers\normalization.py", line 125, in build
    trainable=True)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 349, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1389, in wrapped_custom_getter
    *args, **kwargs)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\layers\base.py", line 275, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\layers\base.py", line 228, in _add_variable
    trainable=trainable and self.trainable)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1334, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1326, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 262, in model_variable
    use_resource=use_resource)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 217, in variable
    use_resource=use_resource)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 653, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable d_conv1/BatchNorm/beta already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\kuseet\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)


Process finished with exit code 1


![2](https://user-images.githubusercontent.com/18389361/35660700-88344d9e-0748-11e8-8892-38e80e951c0b.PNG)
![3](https://user-images.githubusercontent.com/18389361/35660702-8b56c8da-0748-11e8-89ae-0b0ff44f46a9.PNG)

Thank you for your reply.
When I run the train.py, the terminal show me the above issue.
I try to change reuse=True in the model.py , but errors still exist.

**Comment by manumathewthomas** [comment]
What GPU are you using and how much memory do you have?

**Comment by kurvt** [comment]
My GPU is GTX960M 2G.
I did't use GPU，only CPU(core i7-4720HQ) and 16GB memory.

**Comment by manumathewthomas** [comment]
Can you try it with tensorflow V1.0 or wait for 2-3 days I will update the whole repo.

**Comment by kurvt** [comment]
It seems to work now, thank you!

**Comment by TrinhQuocNguyen** [comment]
Hi Kusset, 
I am facing the same problem like you have done. How did you make it run? thank you!!
